name: Build QHora-301W with NSS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget python3 python3-pip

    - name: Add NSS feed
      run: |
        echo 'src-git nss https://github.com/qosmio/openwrt-ipq' >> feeds.conf.default

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate .config
      run: |
        echo "CONFIG_TARGET_qualcommax=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq807x=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq807x_DEVICE_qhora-301w=y" >> .config

        # NSS 模块
        echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-ifb=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-drv-qdisc=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-drv-pppoe=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-drv-vlan=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-gmac=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-sfe=y" >> .config
        echo "CONFIG_PACKAGE_kmod-qca-nss-cfi=y" >> .config
        echo "CONFIG_PACKAGE_qca-nss-userspace=y" >> .config
        echo "CONFIG_PACKAGE_qca-nss-ecm=y" >> .config

        # RTL8125 驱动
        echo "CONFIG_PACKAGE_kmod-r8125=y" >> .config

        # WiFi 驱动
        echo "CONFIG_PACKAGE_kmod-ath11k=y" >> .config
        echo "CONFIG_PACKAGE_ath11k-firmware-ipq8074=y" >> .config
        echo "CONFIG_PACKAGE_wireless-regdb=y" >> .config

        # Luci 和主题
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-theme-argon=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-firewall=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-opkg=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-ttyd=y" >> .config

        # nlbwmon 流量监控
        echo "CONFIG_PACKAGE_luci-app-nlbwmon=y" >> .config
        echo "CONFIG_PACKAGE_nlbwmon=y" >> .config

        # 系统工具
        echo "CONFIG_PACKAGE_htop=y" >> .config
        echo "CONFIG_PACKAGE_tcpdump=y" >> .config
        echo "CONFIG_PACKAGE_nano=y" >> .config

        # 构建信息
        echo "CONFIG_BUILD_LOG=y" >> .config
        echo "CONFIG_DEVEL=y" >> .config

    - name: Run defconfig
      run: make defconfig

    - name: Compile firmware
      run: make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: QHora301W-NSS
        path: bin/targets/qualcommax/ipq807x/
