name: Build QHora-301W with NSS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Update & install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Generate config for QHora-301W with NSS
      run: |
        cat <<EOF > .config
        CONFIG_TARGET_qualcommax=y
        CONFIG_TARGET_qualcommax_ipq807x=y
        CONFIG_TARGET_qualcommax_ipq807x_DEVICE_qhora-301w=y

# NSS核心驱动
        CONFIG_PACKAGE_kmod-qca-nss-drv=y
        CONFIG_PACKAGE_kmod-qca-nss-ecm=y
        CONFIG_PACKAGE_kmod-qca-nss-ifb=y
        CONFIG_PACKAGE_kmod-qca-nss-drv-qdisc=y
        CONFIG_PACKAGE_kmod-qca-nss-drv-pppoe=y
        CONFIG_PACKAGE_kmod-qca-nss-drv-vlan=y
        CONFIG_PACKAGE_kmod-qca-nss-dp=y
        CONFIG_PACKAGE_kmod-qca-nss-gmac=y

# NSS用户空间加速模块
        CONFIG_PACKAGE_qca-nss-userspace=y
        CONFIG_PACKAGE_qca-nss-ecm=y

# NSS 辅助模块
        CONFIG_PACKAGE_kmod-qca-nss-sfe=y
        CONFIG_PACKAGE_kmod-qca-nss-cfi=y

# 网络与Luci界面
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-app-opkg=y
        CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
        CONFIG_PACKAGE_nftables=y
        CONFIG_PACKAGE_dnsmasq-full=y

# WiFi 驱动
        CONFIG_PACKAGE_kmod-ath11k=y
        CONFIG_PACKAGE_ath11k-firmware-ipq8074=y
        CONFIG_PACKAGE_wireless-regdb=y

# 系统工具
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_tcpdump=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_luci-app-ttyd=y

# 其他
        CONFIG_DEVEL=y
        CONFIG_BUILD_LOG=y
        EOF

    - name: Run defconfig
      run: make defconfig

    - name: Compile firmware
      run: make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: QHora301W-NSS
        path: bin/targets/qualcommax/ipq807x/
