name: Build QHora-301W with NSS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom config
      run: |
        curl -Lo .config https://raw.githubusercontent.com/${{ github.repository }}/main/qhora301w-nss.config

    - name: Make defconfig
      run: make defconfig

    - name: Build firmware
      run: make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: QHora301W-NSS
        path: bin/targets/qualcommax/ipq807x/
